### ISSUE TITLE
LINE_NOTIFY_TOKEN

### ISSUE THREAD

**Issue by Wen516** [steveyeh9872/stock_news#1]

**Comment by steveyeh9872** [comment]
1. 在 GitHub 的 repository 設置中添加 LINE_NOTIFY_TOKEN：

進入你的 repository
點擊 "Settings" > "Secrets and variables" > "Actions"
點擊 "New repository secret"
名稱輸入 LINE_NOTIFY_TOKEN
值輸入你的 Line Notify token

2. 要獲取 Line Notify token，請按照以下步驟：

登入 Line Notify：https://notify-bot.line.me/
點擊右上角的 "個人頁面"
選擇 "發行權杖"
為您的權杖命名（例如 "股市通知"），並選擇要接收通知的聊天室或群組
點擊 "發行"，然後複製生成的權杖
